accessManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/access-manager
      tag: v0.33.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
addonController:
  controller:
    args:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --shard-key=
    - --v=5
    - --version=v0.33.0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --shard-key=
    - --v=5
    - --version=v0.33.0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/addon-controller
      tag: v0.33.0
    resources:
      requests:
        memory: 256Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
classifierManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --shard-key=
    - --v=5
    - --version=v0.33.0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --shard-key=
    - --v=5
    - --version=v0.33.0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/classifier
      tag: v0.33.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
conversionWebhook:
  replicas: 1
  sveltosWebhook:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/webhook-conversion
      tag: v0.33.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
eventManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/event-manager
      tag: v0.33.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
hcManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/healthcheck-manager
      tag: v0.33.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
kubernetesClusterDomain: cluster.local
registerMgmtClusterJob:
  backoffLimit: 4
  registerMgmtCluster:
    args:
    - --labels=
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/register-mgmt-cluster
      tag: v0.33.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 128Mi
scManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/sveltoscluster-manager
      tag: v0.33.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
shardController:
  manager:
    args:
    - --diagnostics-address=:8443
    - --v=5
    - --report-mode=0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --v=5
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: projectsveltos/shard-controller
      tag: v0.33.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
prometheus:
  enabled: false
agent:
  managementCluster: false
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
